### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Magnetapfel** [Voxter256/Secret-Santa-Bot#2]
Thx for the bot,
In use we found the following issue. if you use it in a bigger group it's hard to keep track of how many people have joined secret Santa.

It would be great to have a list feature where you can see who has joined.

I hope it's the right way to suggest something (never used GitHub before 😅)

**Comment by Voxter256** [comment]
Thank you for the great suggestion @Magnetapfel ! I implemented and committed it today: https://github.com/Voxter256/Secret-Santa-Bot/commit/f5c9aab16e144b988c38323c6d4b25041eb0cb08

This change is currently live and accessible with the `/status` command
