### ISSUE TITLE
Status of the bot?

### ISSUE THREAD

**Issue by avivace** [Voxter256/Secret-Santa-Bot#5]
Hi! I was trying to use the public instance of the bot, however:

- After sending `/not`, any following `/allow` doesn't work, leaving you unable to undo the exclusion
- Bot accepts `/join`s, but it's not replying on `/status`

**Comment by Voxter256** [comment]
Hey @avivace 
The linked pull request has the changes that should resolve the issue. The bot is currently running on this issue's branch, so let me know if this resolves everything!

**Comment by avivace** [comment]
Looks like it's fixed! Thank you!
