### ISSUE TITLE
Santa Bot down?

### ISSUE THREAD

**Issue by Magnetapfel** [Voxter256/Secret-Santa-Bot#9]
Hey there,
I have been using the bot for the last two year and I wanted to use it this year too. It seems that the bot isn't responding to messages anymore.

Do you plan to make it work again?

Sadly I don't know how to code yet..

Best wishes

**Comment by Voxter256** [comment]
Thank you for the interest! I just booted it back up, so it should be good to go! Let me know if you run into issues either here or in Telegram https://t.me/Voxter256
